# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "tty-font", "~> 0.5.0"

gem "tty-box", "~> 0.5.0"

gem "lolize", "~> 0.0.3"

gem "test", "~> 1.0"

gem "terminal-table", "~> 1.8"
